/* THIS FILE WAS GENERATED BY scripts/generate-importmap.mjs */
import { S3ClientUploadHandler as S3ClientUploadHandler_0 } from '@payloadcms/storage-s3/client';
import { RichTextField as RichTextField_1 } from '@payloadcms/richtext-lexical/client';
import { InlineToolbarFeatureClient as InlineToolbarFeatureClient_2 } from '@payloadcms/richtext-lexical/client';
import { FixedToolbarFeatureClient as FixedToolbarFeatureClient_3 } from '@payloadcms/richtext-lexical/client';
import { BoldFeatureClient as BoldFeatureClient_4 } from '@payloadcms/richtext-lexical/client';
import { ItalicFeatureClient as ItalicFeatureClient_5 } from '@payloadcms/richtext-lexical/client';
import { UnderlineFeatureClient as UnderlineFeatureClient_6 } from '@payloadcms/richtext-lexical/client';
import { StrikethroughFeatureClient as StrikethroughFeatureClient_7 } from '@payloadcms/richtext-lexical/client';
import { SubscriptFeatureClient as SubscriptFeatureClient_8 } from '@payloadcms/richtext-lexical/client';
import { SuperscriptFeatureClient as SuperscriptFeatureClient_9 } from '@payloadcms/richtext-lexical/client';
import { InlineCodeFeatureClient as InlineCodeFeatureClient_10 } from '@payloadcms/richtext-lexical/client';
import { ParagraphFeatureClient as ParagraphFeatureClient_11 } from '@payloadcms/richtext-lexical/client';
import { HeadingFeatureClient as HeadingFeatureClient_12 } from '@payloadcms/richtext-lexical/client';
import { AlignFeatureClient as AlignFeatureClient_13 } from '@payloadcms/richtext-lexical/client';
import { IndentFeatureClient as IndentFeatureClient_14 } from '@payloadcms/richtext-lexical/client';
import { UnorderedListFeatureClient as UnorderedListFeatureClient_15 } from '@payloadcms/richtext-lexical/client';
import { OrderedListFeatureClient as OrderedListFeatureClient_16 } from '@payloadcms/richtext-lexical/client';
import { ChecklistFeatureClient as ChecklistFeatureClient_17 } from '@payloadcms/richtext-lexical/client';
import { LinkFeatureClient as LinkFeatureClient_18 } from '@payloadcms/richtext-lexical/client';
import { RelationshipFeatureClient as RelationshipFeatureClient_19 } from '@payloadcms/richtext-lexical/client';
import { BlockquoteFeatureClient as BlockquoteFeatureClient_20 } from '@payloadcms/richtext-lexical/client';
import { UploadFeatureClient as UploadFeatureClient_21 } from '@payloadcms/richtext-lexical/client';
import { HorizontalRuleFeatureClient as HorizontalRuleFeatureClient_22 } from '@payloadcms/richtext-lexical/client';
import { MetaDescriptionComponent as MetaDescriptionComponent_23 } from '@payloadcms/plugin-seo/client';
import { MetaImageComponent as MetaImageComponent_24 } from '@payloadcms/plugin-seo/client';
import { MetaTitleComponent as MetaTitleComponent_25 } from '@payloadcms/plugin-seo/client';
import { OverviewComponent as OverviewComponent_26 } from '@payloadcms/plugin-seo/client';
import { PreviewComponent as PreviewComponent_27 } from '@payloadcms/plugin-seo/client';
import Logo_custom from '/components/admin/Logo';
import Icon_custom from '/components/admin/Icon';
import DashboardStats_custom from '/components/admin/DashboardStats';

export const importMap = {
  '@payloadcms/storage-s3/client#S3ClientUploadHandler': S3ClientUploadHandler_0,
  '@payloadcms/richtext-lexical/client#RichTextField': RichTextField_1,
  '@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient': InlineToolbarFeatureClient_2,
  '@payloadcms/richtext-lexical/client#FixedToolbarFeatureClient': FixedToolbarFeatureClient_3,
  '@payloadcms/richtext-lexical/client#BoldFeatureClient': BoldFeatureClient_4,
  '@payloadcms/richtext-lexical/client#ItalicFeatureClient': ItalicFeatureClient_5,
  '@payloadcms/richtext-lexical/client#UnderlineFeatureClient': UnderlineFeatureClient_6,
  '@payloadcms/richtext-lexical/client#StrikethroughFeatureClient': StrikethroughFeatureClient_7,
  '@payloadcms/richtext-lexical/client#SubscriptFeatureClient': SubscriptFeatureClient_8,
  '@payloadcms/richtext-lexical/client#SuperscriptFeatureClient': SuperscriptFeatureClient_9,
  '@payloadcms/richtext-lexical/client#InlineCodeFeatureClient': InlineCodeFeatureClient_10,
  '@payloadcms/richtext-lexical/client#ParagraphFeatureClient': ParagraphFeatureClient_11,
  '@payloadcms/richtext-lexical/client#HeadingFeatureClient': HeadingFeatureClient_12,
  '@payloadcms/richtext-lexical/client#AlignFeatureClient': AlignFeatureClient_13,
  '@payloadcms/richtext-lexical/client#IndentFeatureClient': IndentFeatureClient_14,
  '@payloadcms/richtext-lexical/client#UnorderedListFeatureClient': UnorderedListFeatureClient_15,
  '@payloadcms/richtext-lexical/client#OrderedListFeatureClient': OrderedListFeatureClient_16,
  '@payloadcms/richtext-lexical/client#ChecklistFeatureClient': ChecklistFeatureClient_17,
  '@payloadcms/richtext-lexical/client#LinkFeatureClient': LinkFeatureClient_18,
  '@payloadcms/richtext-lexical/client#RelationshipFeatureClient': RelationshipFeatureClient_19,
  '@payloadcms/richtext-lexical/client#BlockquoteFeatureClient': BlockquoteFeatureClient_20,
  '@payloadcms/richtext-lexical/client#UploadFeatureClient': UploadFeatureClient_21,
  '@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient': HorizontalRuleFeatureClient_22,
  '@payloadcms/plugin-seo/client#MetaDescriptionComponent': MetaDescriptionComponent_23,
  '@payloadcms/plugin-seo/client#MetaImageComponent': MetaImageComponent_24,
  '@payloadcms/plugin-seo/client#MetaTitleComponent': MetaTitleComponent_25,
  '@payloadcms/plugin-seo/client#OverviewComponent': OverviewComponent_26,
  '@payloadcms/plugin-seo/client#PreviewComponent': PreviewComponent_27,
  '/components/admin/Logo#default': Logo_custom,
  '/components/admin/Icon#default': Icon_custom,
  '/components/admin/DashboardStats#default': DashboardStats_custom,
};
