/* THIS FILE WAS GENERATED BY scripts/generate-importmap.mjs */
import { RscEntryLexicalCell as RscEntryLexicalCell_0 } from '@payloadcms/richtext-lexical/rsc';
import { RscEntryLexicalField as RscEntryLexicalField_1 } from '@payloadcms/richtext-lexical/rsc';
import { LexicalDiffComponent as LexicalDiffComponent_2 } from '@payloadcms/richtext-lexical/rsc';
import { S3ClientUploadHandler as S3ClientUploadHandler_3 } from '@payloadcms/storage-s3/client';
import { CollectionCards as CollectionCards_4 } from '@payloadcms/next/rsc';
import { RichTextField as RichTextField_5 } from '@payloadcms/richtext-lexical/client';
import { InlineToolbarFeatureClient as InlineToolbarFeatureClient_6 } from '@payloadcms/richtext-lexical/client';
import { FixedToolbarFeatureClient as FixedToolbarFeatureClient_7 } from '@payloadcms/richtext-lexical/client';
import { BoldFeatureClient as BoldFeatureClient_8 } from '@payloadcms/richtext-lexical/client';
import { ItalicFeatureClient as ItalicFeatureClient_9 } from '@payloadcms/richtext-lexical/client';
import { UnderlineFeatureClient as UnderlineFeatureClient_10 } from '@payloadcms/richtext-lexical/client';
import { StrikethroughFeatureClient as StrikethroughFeatureClient_11 } from '@payloadcms/richtext-lexical/client';
import { SubscriptFeatureClient as SubscriptFeatureClient_12 } from '@payloadcms/richtext-lexical/client';
import { SuperscriptFeatureClient as SuperscriptFeatureClient_13 } from '@payloadcms/richtext-lexical/client';
import { InlineCodeFeatureClient as InlineCodeFeatureClient_14 } from '@payloadcms/richtext-lexical/client';
import { ParagraphFeatureClient as ParagraphFeatureClient_15 } from '@payloadcms/richtext-lexical/client';
import { HeadingFeatureClient as HeadingFeatureClient_16 } from '@payloadcms/richtext-lexical/client';
import { AlignFeatureClient as AlignFeatureClient_17 } from '@payloadcms/richtext-lexical/client';
import { IndentFeatureClient as IndentFeatureClient_18 } from '@payloadcms/richtext-lexical/client';
import { UnorderedListFeatureClient as UnorderedListFeatureClient_19 } from '@payloadcms/richtext-lexical/client';
import { OrderedListFeatureClient as OrderedListFeatureClient_20 } from '@payloadcms/richtext-lexical/client';
import { ChecklistFeatureClient as ChecklistFeatureClient_21 } from '@payloadcms/richtext-lexical/client';
import { LinkFeatureClient as LinkFeatureClient_22 } from '@payloadcms/richtext-lexical/client';
import { RelationshipFeatureClient as RelationshipFeatureClient_23 } from '@payloadcms/richtext-lexical/client';
import { BlockquoteFeatureClient as BlockquoteFeatureClient_24 } from '@payloadcms/richtext-lexical/client';
import { UploadFeatureClient as UploadFeatureClient_25 } from '@payloadcms/richtext-lexical/client';
import { HorizontalRuleFeatureClient as HorizontalRuleFeatureClient_26 } from '@payloadcms/richtext-lexical/client';
import { TextStateFeatureClient as TextStateFeatureClient_27 } from '@payloadcms/richtext-lexical/client';
import { TableFeatureClient as TableFeatureClient_28 } from '@payloadcms/richtext-lexical/client';
import { BlocksFeatureClient as BlocksFeatureClient_29 } from '@payloadcms/richtext-lexical/client';
import { MetaDescriptionComponent as MetaDescriptionComponent_30 } from '@payloadcms/plugin-seo/client';
import { MetaImageComponent as MetaImageComponent_31 } from '@payloadcms/plugin-seo/client';
import { MetaTitleComponent as MetaTitleComponent_32 } from '@payloadcms/plugin-seo/client';
import { OverviewComponent as OverviewComponent_33 } from '@payloadcms/plugin-seo/client';
import { PreviewComponent as PreviewComponent_34 } from '@payloadcms/plugin-seo/client';
import { LinkToDoc as LinkToDoc_35 } from '@payloadcms/plugin-search/client';
import { ReindexButton as ReindexButton_36 } from '@payloadcms/plugin-search/client';
import Logo_custom from '../../../components/admin/Logo';
import Icon_custom from '../../../components/admin/Icon';
import DashboardStats_custom from '../../../components/admin/DashboardStats';
import AnalyticsDashboard_custom from '../../../components/admin/AnalyticsDashboard';

export const importMap = {
  '@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell': RscEntryLexicalCell_0,
  '@payloadcms/richtext-lexical/rsc#RscEntryLexicalField': RscEntryLexicalField_1,
  '@payloadcms/richtext-lexical/rsc#LexicalDiffComponent': LexicalDiffComponent_2,
  '@payloadcms/storage-s3/client#S3ClientUploadHandler': S3ClientUploadHandler_3,
  '@payloadcms/next/rsc#CollectionCards': CollectionCards_4,
  '@payloadcms/richtext-lexical/client#RichTextField': RichTextField_5,
  '@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient': InlineToolbarFeatureClient_6,
  '@payloadcms/richtext-lexical/client#FixedToolbarFeatureClient': FixedToolbarFeatureClient_7,
  '@payloadcms/richtext-lexical/client#BoldFeatureClient': BoldFeatureClient_8,
  '@payloadcms/richtext-lexical/client#ItalicFeatureClient': ItalicFeatureClient_9,
  '@payloadcms/richtext-lexical/client#UnderlineFeatureClient': UnderlineFeatureClient_10,
  '@payloadcms/richtext-lexical/client#StrikethroughFeatureClient': StrikethroughFeatureClient_11,
  '@payloadcms/richtext-lexical/client#SubscriptFeatureClient': SubscriptFeatureClient_12,
  '@payloadcms/richtext-lexical/client#SuperscriptFeatureClient': SuperscriptFeatureClient_13,
  '@payloadcms/richtext-lexical/client#InlineCodeFeatureClient': InlineCodeFeatureClient_14,
  '@payloadcms/richtext-lexical/client#ParagraphFeatureClient': ParagraphFeatureClient_15,
  '@payloadcms/richtext-lexical/client#HeadingFeatureClient': HeadingFeatureClient_16,
  '@payloadcms/richtext-lexical/client#AlignFeatureClient': AlignFeatureClient_17,
  '@payloadcms/richtext-lexical/client#IndentFeatureClient': IndentFeatureClient_18,
  '@payloadcms/richtext-lexical/client#UnorderedListFeatureClient': UnorderedListFeatureClient_19,
  '@payloadcms/richtext-lexical/client#OrderedListFeatureClient': OrderedListFeatureClient_20,
  '@payloadcms/richtext-lexical/client#ChecklistFeatureClient': ChecklistFeatureClient_21,
  '@payloadcms/richtext-lexical/client#LinkFeatureClient': LinkFeatureClient_22,
  '@payloadcms/richtext-lexical/client#RelationshipFeatureClient': RelationshipFeatureClient_23,
  '@payloadcms/richtext-lexical/client#BlockquoteFeatureClient': BlockquoteFeatureClient_24,
  '@payloadcms/richtext-lexical/client#UploadFeatureClient': UploadFeatureClient_25,
  '@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient': HorizontalRuleFeatureClient_26,
  '@payloadcms/richtext-lexical/client#TextStateFeatureClient': TextStateFeatureClient_27,
  '@payloadcms/richtext-lexical/client#TableFeatureClient': TableFeatureClient_28,
  '@payloadcms/richtext-lexical/client#BlocksFeatureClient': BlocksFeatureClient_29,
  '@payloadcms/plugin-seo/client#MetaDescriptionComponent': MetaDescriptionComponent_30,
  '@payloadcms/plugin-seo/client#MetaImageComponent': MetaImageComponent_31,
  '@payloadcms/plugin-seo/client#MetaTitleComponent': MetaTitleComponent_32,
  '@payloadcms/plugin-seo/client#OverviewComponent': OverviewComponent_33,
  '@payloadcms/plugin-seo/client#PreviewComponent': PreviewComponent_34,
  '@payloadcms/plugin-search/client#LinkToDoc': LinkToDoc_35,
  '@payloadcms/plugin-search/client#ReindexButton': ReindexButton_36,
  '/components/admin/Logo#default': Logo_custom,
  '/components/admin/Icon#default': Icon_custom,
  '/components/admin/DashboardStats#default': DashboardStats_custom,
  '/components/admin/AnalyticsDashboard#default': AnalyticsDashboard_custom,
};
